---
collections:
  - name: https://github.com/sean-m-sullivan/ee_definition_config/raw/main/redhat_cop-ee_utilities-1.0.2.tar.gz
    version: 1.0.2
  - name: awx.awx
  - name: redhat_cop.controller_configuration
  - name: containers.podman
...
