---
- name: Using role create job template
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: https://controller.nas/
    controller_username: admin
    controller_password: secret123
    controller_validate_certs: false
    controller_configuration_async_delay: 3
    controller_projects:
      - name: EE build project
        scm_type: git
        scm_url: https://github.com/sean-m-sullivan/ee_definition_config.git
        scm_branch: main
        scm_update_on_launch: false
        description: EE build project
        organization: Default
        wait: true
        update: false
    controller_inventories:
      - name: AAP Hosts
        organization: Default
      - name: Blank (localhost only)
        organization: Default
    controller_hosts:
      - name: 10.242.42.143
        inventory: AAP Hosts
        variables:
          ansible_connection: ssh
          ansible_ssh_user: awx
          ansible_ssh_pass: password
      - name: localhost
        inventory: Blank (localhost only)
        variables:
          ansible_connection: local
    controller_credential_types:
      - name: Registry Credentials
        description: REST API Credential
        kind: cloud
        inputs:
          fields:
            - id: base_registery_username
              type: string
              label: RH Registery Username
            - id: base_registery_password
              type: string
              label: RH Registery Password
              secret: true
            - id: ee_registry_username
              type: string
              label: AH Registery Username
            - id: ee_registry_password
              type: string
              label: AH Registery Password
              secret: true
            - id: ah_host
              type: string
              label: AH Hostname
            - id: ah_token
              type: string
              label: AH Token
              secret: true
            - id: ee_validate_certs
              type: boolean
              default: false
              label: Validate certs
          required:
            - base_registery_username
            - base_registery_password
        injectors:
          extra_vars:
            ee_base_registry_username: !unsafe "{{ base_registery_username }}"
            ee_base_registry_password: !unsafe "{{ base_registery_password }}"
            ee_registry_username: !unsafe "{{ ee_registry_username }}"
            ee_registry_password: !unsafe "{{ ee_registry_password }}"
            ee_validate_certs: !unsafe "{{ ee_validate_certs }}"
            ah_host: !unsafe "{{ ah_host }}"
            ah_token: !unsafe "{{ ah_token }}"
    controller_credentials:
      - credential_type: Registry Credentials
        name: Execution Build Credentials
        organization: Default
        inputs:
          base_registery_username: rhn-username
          base_registery_password: !vault |
                    $ANSIBLE_VAULT;1.1;AES256
                    38343138643736376337626664646137363764393037396162643730346234663035646562646338
                    6531323731363538353063383661326334626234363834660a623463396433653034343934336466
                    32363431646462313966323633343837656666643935353561323663616266323962643435303034
                    6239363439666330350a653062306361363966336236363332326265653366386334316533323763
                    3238
          ee_registry_username: admin
          ee_registry_password: secret123
          ee_validate_certs: false
          ah_host: hub.nas
          ah_token: 16fd981f4fc296befe8374ab453ddd4f541deb5b
      - credential_type: Red Hat Ansible Automation Platform
        name: Controller Credential
        organization: Default
        inputs:
          host: 10.242.42.150
          username: admin
          password: secret123
          verify_ssl: false
    controller_templates:
      - name: Execution Environment Builder
        job_type: run
        inventory: AAP Hosts
        credentials:
          - Execution Build Credentials
        project: EE build project
        execution_environment: Automation Hub Minimal execution environment
        playbook: ee_builder_controller.yaml
        extra_vars:
          ee_registry_dest: hub.nas
          ee_builder_dir_clean: true
      - name: Push Execution Environments to Controller
        job_type: run
        inventory: Blank (localhost only)
        credentials:
          - Controller Credential
        project: EE build project
        execution_environment: Automation Hub Minimal execution environment
        playbook: push_to_controller.yaml
    controller_workflows:
      - name: Update Execution Environments
        workflow_nodes:
          - identifier: Build EE's
            unified_job_template:
              name: Execution Environment Builder
              type: job_template
              organization:
                name: Default
            related:
              success_nodes:
                - identifier: Push EE's to controller
          - identifier: Push EE's to controller
            unified_job_template:
              name: Push Execution Environments to Controller
              type: job_template
              organization:
                name: Default
  collections:
    - ansible.controller
    - infra.controller_configuration
  roles:
    - infra.controller_configuration.credential_types
    - infra.controller_configuration.credentials
    - infra.controller_configuration.inventories
    - infra.controller_configuration.hosts
    - infra.controller_configuration.projects
    - infra.controller_configuration.job_templates
    - infra.controller_configuration.workflow_job_templates
...
