---
- name: Playbook to create custom EE
  hosts: localhost # controller.node
  gather_facts: false
  collections:
    - redhat_cop.ee_utilities
  vars:
    ee_registry_dest: ahnosso.node
    ee_builder_dir_clean: true
    base_registery_username: rhn-gps-ssulliva
    base_registery_password: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              38343138643736376337626664646137363764393037396162643730346234663035646562646338
              6531323731363538353063383661326334626234363834660a623463396433653034343934336466
              32363431646462313966323633343837656666643935353561323663616266323962643435303034
              6239363439666330350a653062306361363966336236363332326265653366386334316533323763
              3238
    ee_ah_host: ahnosso.node
    ee_ah_token: 4ab76668c4b2622ab1dfb7cbee7e6c9b8e62c0f5
    ee_registry_username: admin
    ee_registry_password: secret123
    ee_list:
      - name: custom_ee
        # base_image
        bindep:
          - python38-requests [platform:centos-8 platform:rhel-8]
          - python38-pyyaml [platform:centos-8 platform:rhel-8]
        python:
          - pytz  # for schedule_rrule lookup plugin
          - python-dateutil>=2.7.0  # schedule_rrule
          - awxkit  # For import and export modules
        collections:
          - name: awx.awx
            version: 12.0.0
          - name: redhat_cop.controller_configuration
          - name: redhat_cop.ah_configuration
        prepend:
          - RUN whoami
          - RUN cat /etc/os-release
        append:
          - RUN echo This is a post-install command!
  roles:
    - redhat_cop.ee_utilities.ee_builder
...
