---
- name: Playbook to create custom EE
  hosts: all
  gather_facts: false

  tasks:
    - name: Add Execution Environment
      ansible.builtin.include_role:
        name: infra.controller_configuration.execution_environments
...
